// The arithmetic two processors both need, in one place.
//
// This is a deliberately narrow extraction. What moved here is the per-sample maths that is
// genuinely identical between the ladder and the wavetable - a four-pole filter and two envelope
// shapes - and nothing else. Voice pools, event queues and modulation routing stayed where they
// are, even though they look similar from a distance, because they are not the same: a wavetable
// voice carries a bank of unison phases and a mip level, and a routing table is written in terms
// of destinations that differ per instrument. Sharing those would have meant a base class with
// hooks, which is a lot of indirection on the audio thread to avoid retyping a for-loop.
//
// The line is: share the arithmetic, not the architecture. The arithmetic is what would drift
// silently - a filter that is subtly different in two instruments sounds like two instruments, and
// nobody would ever find it.
//
// Same rules as the processors that call this. Nothing allocates, nothing closes over anything,
// and everything takes the voice and mutates it in place, because the alternative is returning
// objects several million times a second.

/**
 * PolyBLEP: the correction that turns a naive ramp or square into something worth listening to.
 *
 * A waveform generated by counting up and wrapping has a vertical edge in it, and a vertical edge
 * has infinite bandwidth - every harmonic above Nyquist folds back down as an inharmonic partial.
 * The fix is to notice that the only unbounded part is the discontinuity itself, and to round it
 * off over the couple of samples either side using a polynomial fitted to a band-limited step.
 *
 * Shared because the cymbals want it too. A metallic voice is six squares summed and filtered, and
 * it would be very easy to argue that aliasing does not matter in something already inharmonic and
 * broadband - which is true right up until the scope is pointed at it and reports the number this
 * whole project exists to keep honest. Cheaper to band-limit it than to explain it.
 */
export function polyBlep(t, dt) {
  if (t < dt) {
    const x = t / dt;
    return x + x - x * x - 1;
  }
  if (t > 1 - dt) {
    const x = (t - 1) / dt;
    return x * x + x + x + 1;
  }
  return 0;
}

/** A band-limited square from a phase in turns. `inc` is the phase step, which sets the correction width. */
export function squareAt(phase, inc) {
  let out = phase < 0.5 ? 1 : -1;
  out += polyBlep(phase, inc);
  let half = phase + 0.5;
  if (half >= 1) half -= 1;
  return out - polyBlep(half, inc);
}

export const MAX_UNISON = 7;

/**
 * Where each unison copy sits, in units of the detune spread, for a given count.
 *
 * Spread symmetrically around the note, with one copy exactly on it when the count is odd, so
 * turning unison up thickens a sound without moving its pitch.
 *
 * Here rather than in the processor because the scope needs it too. Detuned copies put their
 * harmonics at their own frequencies rather than at multiples of the note, so an analyser that did
 * not know the spread would report every one of them as an unasked-for partial - which is the exact
 * failure the `partials` hook was generalised to avoid. One definition, so the picture and the sound
 * cannot disagree about where the copies are.
 */
export function unisonOffsets(count) {
  const n = count < 1 ? 1 : count > MAX_UNISON ? MAX_UNISON : Math.round(count);
  const row = new Float64Array(n);
  for (let i = 0; i < n; i++) row[i] = n === 1 ? 0 : (i / (n - 1)) * 2 - 1;
  return row;
}

/**
 * Amplitude compensation for `count` detuned copies.
 *
 * Detuned copies are not coherent, so they sum as power rather than as amplitude - dividing by the
 * count would make unison quieter instead of thicker, which is the mistake that makes people
 * reach for the level knob every time they touch it.
 */
export function unisonScale(count) {
  return 1 / Math.sqrt(count < 1 ? 1 : count);
}

/**
 * One sample through four one-pole stages inside a saturating feedback loop.
 *
 * `g` is the per-sample coefficient for the cutoff - `1 - exp(-2*pi*fc/sr)` - computed by the
 * caller because it is the same for every voice in a quantum and belongs outside the voice loop.
 *
 * tanh in the feedback path is the nonlinearity, and it is most of the character: it is what keeps
 * a self-oscillating filter bounded rather than exploding, and it is the difference between "a
 * filter with a peak" and the sound people mean when they say ladder.
 */
export function ladderStep(v, input, g, k, drive) {
  const shaped = Math.tanh(input * drive - k * v.s4);
  v.s1 += g * (shaped - v.s1);
  v.s2 += g * (v.s1 - v.s2);
  v.s3 += g * (v.s2 - v.s3);
  v.s4 += g * (v.s3 - v.s4);
  return v.s4;
}

/**
 * Advance the amplitude envelope one sample. Returns false when the note has finished and the
 * voice can be freed.
 *
 * Rates are in level-per-sample, computed once per quantum by the caller: parameters cannot change
 * inside a quantum anyway, since messages are delivered between them, so recomputing them per
 * sample would be 128 times the work for the same answer.
 *
 * Stages: 1 attack, 2 decay, 3 sustain, 4 release. Held as a level and a segment rather than as
 * scheduled ramps because there is no scheduler down here - this is the thing that would have been
 * doing the scheduling.
 */
export function stepAmp(v, attack, decay, release, sustain) {
  if (v.ampStage === 1) {
    v.ampLevel += attack;
    if (v.ampLevel >= 1) {
      v.ampLevel = 1;
      v.ampStage = 2;
    }
  } else if (v.ampStage === 2) {
    v.ampLevel -= decay * (1 - sustain);
    if (v.ampLevel <= sustain) {
      v.ampLevel = sustain;
      v.ampStage = 3;
    }
  } else if (v.ampStage === 4) {
    v.ampLevel -= release * v.releaseFrom;
    if (v.ampLevel <= 0) {
      v.ampLevel = 0;
      return false;
    }
  }
  return true;
}

/**
 * The same shape for a modulation envelope, which differs in exactly one way: reaching zero on
 * release ends a note but does not end a *sweep*. A filter envelope that hit zero and freed the
 * voice would cut the note off at the moment the filter closed, which is not what closing a filter
 * means.
 */
export function stepEnv(v, attack, decay, release, sustain) {
  if (v.envStage === 1) {
    v.envLevel += attack;
    if (v.envLevel >= 1) {
      v.envLevel = 1;
      v.envStage = 2;
    }
  } else if (v.envStage === 2) {
    v.envLevel -= decay * (1 - sustain);
    if (v.envLevel <= sustain) {
      v.envLevel = sustain;
      v.envStage = 3;
    }
  } else if (v.envStage === 4) {
    v.envLevel -= release * v.envReleaseFrom;
    if (v.envLevel < 0) v.envLevel = 0;
  }
}

/** Level-per-sample for a stage of `seconds`, floored so that a zero-length stage is one sample. */
export function rateFor(seconds, sampleRate) {
  return 1 / Math.max(1, seconds * sampleRate);
}

export const CUTOFF_MIN_HZ = 20;
export const CUTOFF_MAX_HZ = 18000;

/**
 * Where the cutoff actually sits, given a base in Hz and a displacement in octaves.
 *
 * Octaves rather than Hz for the reason everything else in this project is: the ear reads frequency
 * logarithmically, so octaves are the unit in which one setting means one gesture at any pitch. The
 * displacements are summed *in the exponent*, which is why an envelope and an LFO aimed at the same
 * cutoff combine the way they read in the panel - +2 and ±1 is a sweep that wobbles, not a sweep
 * multiplied by a wobble.
 */
export function cutoffHz(base, octaves) {
  const fc = base * Math.pow(2, octaves);
  if (fc > CUTOFF_MAX_HZ) return CUTOFF_MAX_HZ;
  if (fc < CUTOFF_MIN_HZ) return CUTOFF_MIN_HZ;
  return fc;
}

/**
 * Amplitude with a modulation contribution that cannot outlive the note, scaled by how hard the
 * note was struck.
 *
 * Velocity multiplies the *result* rather than the envelope, so a tremolo's depth stays a fixed
 * fraction of the note it is on rather than being modulated twice.
 *
 * A tremolo that keeps adding to the amp gain after the release ramp has reached zero is a note
 * that never stops, so the contribution is scaled by how much of the release is left. The
 * node-graph instruments do the same thing by ramping the routing's gain down; here it is one
 * multiply.
 */
export function amplitudeWithMod(v) {
  if (v.modGain === 0) return v.ampLevel * v.velocity;
  const amp = v.ampLevel + (v.ampStage === 4 && v.releaseFrom > 1e-6
    ? v.modGain * (v.ampLevel / v.releaseFrom)
    : v.modGain);
  return amp < 0 ? 0 : amp * v.velocity;
}
